import type { TranslationKey } from "./Translations";

const MAP: Record<string, TranslationKey> = {
    invalid_credentials: "auth.errInvalidCredentials",
    invalid_code: "login.invalidCode",
    invalid_name: "auth.errInvalidName",
    invalid_email: "auth.errInvalidEmail",
    weak_password: "auth.errWeakPassword",
    password_mismatch: "auth.errMismatch",
    email_taken: "auth.errEmailTaken",
    rate_limited: "auth.errRateLimit",
    network: "auth.errNetwork",
    code_expired: "code.errExpired",
    class_closed: "code.errClassClosed",
    already_member: "code.errAlreadyMember",
    teachers_cannot_join: "code.errTeacherCannotJoin",
    invalid_class_name: "classes.errName",
    already_teacher: "classes.errAlreadyTeacher",
    owner_only: "classes.errOwnerOnly",
    owner_cannot_leave: "classes.errOwnerCannotLeave",
    class_archived: "classes.errArchived",
    invite_not_found: "classes.errInviteNotFound",
    wrong_password: "auth.errWrongPassword",
    invalid_reset_code: "reset.errInvalidCode",
    file_too_large: "media.errTooLarge",
    storage_full: "media.errStorageFull",
    unsupported_media: "media.errUnsupported",
    not_saved: "handIn.errNotSaved",
    no_work: "handIn.errNoWork",
    not_published: "handIn.errNotPublished",
    invalid_project: "projectEditor.errInvalid",
    too_many_media: "projectEditor.errTooManyMedia",
    not_found: "classes.errNotFound",
    forbidden: "classes.errForbidden",
};

export const authErrorKey = (error: string): TranslationKey => MAP[error] ?? "auth.errGeneric";